#pragma once

#include "NativeGameplayTags.h"

namespace DCTags
{
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Ballistic);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Environmental);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Melee);

	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Firearm);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Ammo);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Medical);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Salvage);

	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Hostile);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Friendly);

	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Pickup);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Loot);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Talk);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Inspect);
	DEADCURRENT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Use);
}
